### ISSUE TITLE
Add UML (Sequence diagram) to all API requests

### ISSUE THREAD

**Issue by asafMasa** [MapColonies/exporter-worker#28]

**Comment by CL-SHLOMIKONCHA** [comment]
![Untitled Diagram](https://user-images.githubusercontent.com/65117898/95437825-2529bc00-095e-11eb-8c09-c082315308f8.png)

**Comment by CL-SHLOMIKONCHA** [comment]
![worker_uml](https://user-images.githubusercontent.com/65117898/95954592-38c49f00-0e04-11eb-9073-45f35cb40820.png)

**Comment by CL-SHLOMIKONCHA** [comment]
![worker_uml](https://user-images.githubusercontent.com/65117898/95991267-3dee1200-0e35-11eb-9788-3d5927e925da.jpg)

**Comment by CL-SHLOMIKONCHA** [comment]
![worker_uml](https://user-images.githubusercontent.com/65117898/95991267-3dee1200-0e35-11eb-9788-3d5927e925da.jpg)

**Comment by CL-SHLOMIKONCHA** [comment]
![uml_worker](https://user-images.githubusercontent.com/65117898/96032133-ea94b780-0e66-11eb-8e03-b24fdd86b553.jpg)
