### ISSUE TITLE
Add Retries Count for each try of GDAL execution

### ISSUE THREAD

**Issue by asafMasa** [MapColonies/exporter-worker#69]

**Comment by CL-SHLOMIKONCHA** [comment]
**Soulotion for immediately retry**
Kafka-python provides seek_to_beginning(), which seek to the oldest available offset for partitions.
I've created an IF statement inside the catch statement while task failed to check the JSON object field ("retries") that i consumes from queue,
and used the seek_to_beginning() to consume the same oldest offset (task) again as long as the "retries" field is a positive integer, when retries is on 0 i commit the task with status failed with no more retries

**Comment by CL-SHLOMIKONCHA** [comment]
Soulotion for commit failed error
Kafka can be configure for a longer timeout for each pull() calls and we will have to set some timeout for Gdal operation
untill we decide to fail it and kill the proccess so gdal wont reach the same timeout as Kafka pull check -> Kafka will be available to commit success/failed jobs.
